name: CI Tests Flask + Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le code
      uses: actions/checkout@v3

    - name:  Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-html

    - name: Lancer les tests unitaires
      run: |
        pytest tests/test_logiciel.py --html=rapport_unitaires.html

    - name:  Lancer le test Selenium (headless)
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox xvfb
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        pytest tests/test_selenium.py --html=rapport_fonctionnel.html

    - name:  Uploader les rapports
      uses: actions/upload-artifact@v4
      with:
        name: rapports-tests
        path: |
          rapport_unitaires.html
          rapport_fonctionnel.html
